export enum Channel {
  'START_CAPTURE_SCREEN' = 'start-capture-screen',
  'SCREENSHOT_CAPTURED' = 'screenshot-captured',
  'STOP_CAPTURE_SCREEN' = 'stop-capture-screen',
  'START_CONVERT_TO_VIDEO' = 'start-convert-screenshot-to-video',
  'SCREESHOTS_CONVERTED' = 'screenshots-converted',
  'CANCEL_CONVERSION' = 'cancel-conversion',
  'CONVERSION_IN_PROGRESS' = 'conversion-progress',
  'CANCEL_GENERATING' = 'cancel-generating',
  'GENERATION_ERROR' = 'generation-error',
  'REQUEST_SCREENSHOTS' = 'request-screeshots',
  'REQUEST_ONE_SCREENSHOT' = 'request::one::screeshots',
  'REQUEST_DELETE_ALL_SCREENSHOTS' = 'request-delete-all-screeshots',
  'REQUEST_PURGE' = 'request-purge',
  'SEARCHING' = 'searching',
  'UPLOAD' = 'upload',
  'UPLOAD_DONE' = 'upload::done',
  'UPLOAD_PROGRESS' = 'upload::progress',
  'UPLOAD_ERROR' = 'upload::error',
  'UPLOAD_CANCELED' = 'upload::canceled',
  'REQUEST_RECENT_VIDEOS' = 'request::recent::video',
}
