const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load environment variables from .env file
const envPath = path.resolve(__dirname, '../.env');
const envConfig = dotenv.config({ path: envPath });

if (envConfig.error) {
  console.warn('Warning: .env file not found or could not be loaded');
  process.exit(0);
}

// Create environment-vars.ts file with the loaded variables
const envVars = envConfig.parsed || {};

// Filter environment variables to only include those we want to expose to the client
const clientEnvVars = {};
Object.keys(envVars).forEach(key => {
  // Only include variables that don't contain sensitive information
  // You can customize this logic based on your needs
  if (!key.toLowerCase().includes('secret') && 
      !key.toLowerCase().includes('password') && 
      !key.toLowerCase().includes('key')) {
    clientEnvVars[key] = envVars[key];
  } else {
    // For sensitive variables, just indicate they exist
    clientEnvVars[key] = '***HIDDEN***';
  }
});

const environmentContent = `// This file is auto-generated by scripts/load-env.js
// Do not edit this file manually

export const environment = {
  production: false,
${Object.entries(clientEnvVars).map(([key, value]) => `  ${key}: ${JSON.stringify(value)}`).join(',\n')}
};
`;

const environmentPath = path.resolve(__dirname, '../apps/ui/src/environment/environment.dev.ts');
fs.writeFileSync(environmentPath, environmentContent);

console.log('Environment variables loaded successfully!');
console.log('Available variables:', Object.keys(clientEnvVars).join(', '));